# Generated by Django 2.2.16 on 2020-09-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200929_0614"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="dfdfasd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
