# Generated by Django 2.2.16 on 2020-09-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhgfghfh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghhfjhfhg',
            old_name='dfgwrhtety',
            new_name='hgjh6546465',
        ),
    ]
