# Generated by Django 2.2.16 on 2020-09-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhgfghfh', '0002_auto_20200929_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghhfjhfhg',
            old_name='dfgrsthgwstrhet',
            new_name='hgfhgfhgf',
        ),
    ]
