# Generated by Django 2.2.16 on 2020-09-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhgfghfh', '0005_auto_20200929_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghhfjhfhg',
            name='hgfhgfhgf',
        ),
        migrations.RemoveField(
            model_name='ghhfjhfhg',
            name='hgjh6546465',
        ),
    ]
